Gemfile, Gemfile.lock, app/models/item.rb, app/models/order.rb, app/models/order_item.rb, app/models/user.rb, db/migrate/20190401224536_create_user.rb, db/migrate/20190401225323_create_items.rb, db/migrate/20190401225537_create_order.rb, db/migrate/20190401225914_create_order_item.rb, db/schema.rb, spec/models/item_spec.rb, spec/models/order_item_spec.rb, spec/models/order_spec.rb, spec/models/user_spec.rb
- Wrote model tests for relationships and validations for user and item
- Created models
- Created database
- All tests passing!
=> Model tests

Gemfile, Gemfile.lock, db/seeds.rb, spec/factories/item.rb, spec/factories/order.rb, spec/factories/order_item.rb, spec/factories/user.rb, spec/features/users/navigation_spec.rb, spec/rails_helper.rb
- Installed FactoryBot Gem
- Updated RSpec configuration in rails_helper
- Implemented a FactoryBot user in the navigation_spec test
- Implemented seed file with FactoryBot objects
- All tests passing except rspec ./spec/features/users/navigation_spec.rb:10, which will be fixed with Smitha's User Story 3 pull request.
=> Implemented FactoryBot

app/controllers/merchants_controller.rb, app/controllers/sessions_controller.rb, app/views/layouts/application.html.erb, app/views/sessions/new.html.erb, app/views/users/show.html.erb, config/routes.rb, spec/features/users/navigation_spec.rb, spec/features/users/registration_spec.rb
Adds tests for registered user navigation.
Adds merchants_controller.
Adds Login form in sessions view.
Adds logout path and corresponding CRUD function in sessions controller.
CRUD function for login added in sessions controller.
All tests are passing.
=> User Navigation

.gitignore, app/controllers/items_controller.rb, app/views/items/index.html.erb, config/routes.rb, spec/features/items/index_spec.rb
Each item displays the following information:
- the name of the item
- a small thumbnail image for the item
- the merchant name who sells the item
- how many of the item the merchant has in stock
- the merchant's current price for the item
The item name is a link to that item's show page
The item thumbnail is a link to that item's show page
=> adds items index, except testing images

app/controllers/users_controller.rb, app/models/order.rb, app/models/user.rb, app/views/users/new.html.erb, spec/features/users/registration_spec.rb, spec/models/user_spec.rb
PULL REQUEST TEMPLATE:
Closes User Story #115:
When I visit the user registration page
And I do not fill in this form completely,
I am returned to the registration page
And I see a flash message indicating that I am missing required fields
- Added validations for required fields in registration
- Added enums for user
- Added enums for order 
=> Registration reqs

app/controllers/application_controller.rb, app/controllers/items_controller.rb, app/controllers/merchants_controller.rb, app/controllers/sessions_controller.rb, app/models/item.rb, app/models/user.rb, app/views/items/index.html.erb, app/views/layouts/application.html.erb, spec/features/items/index_spec.rb, spec/features/users/navigation_spec.rb
added to the where clause so that only active items are displayed.
=> adds items index, only active items

app/controllers/merchants_controller.rb, app/models/user.rb, app/views/merchants/index.html.erb, spec/features/merchants/index_spec.rb, spec/models/user_spec.rb
@hsmitha26 / @erin-king / @stiehlrod 
Closes User Story 39 (#77)
"As a visitor
When I visit the merchant's index page at "/merchants"
I see all merchants in the system who are active
Next to each merchant's name I see their city and state
I also see the date they registered"
- Created feature test for the merchants index page
- Added User model test to find active merchants
- Added all active merchants to the merchants index
- All merchant index tests passing
=> Merchant index

app/controllers/items_controller.rb, app/models/item.rb, app/views/items/index.html.erb, spec/features/items/index_spec.rb, spec/features/users/navigation_spec.rb, spec/models/item_spec.rb
Closes User Story 15:
As any kind of user on the system
When I visit the items index page ("/items")
I see an area with statistics:
- the top 5 most popular items by quantity purchased, plus the quantity bought
- the bottom 5 least popular items, plus the quantity bought
"Popularity" is determined by total quantity of that item fulfilled
- Updated 
modified:   app/controllers/items_controller.rb (white space)
modified:   app/models/item.rb (added class methods)
modified:   app/views/items/index.html.erb (added statistics)
modified:   spec/features/items/index_spec.rb (added it block test)
modified:   spec/features/users/navigation_spec.rb (skipped a test)
modified:   spec/models/item_spec.rb (model tests)
=> adds story15

app/controllers/merchants_controller.rb, app/views/layouts/application.html.erb, app/views/merchants/show.html.erb, config/routes.rb, spec/features/users/navigation_spec.rb
- feature tests for navigation are passing.
- Please note: lines related to before(:each) in the test are commented out as this was causing the wrong nav bars to render.
- There is still an error for items index feature test that is not yet resolved.
=> completes user story 4, all navigation tests are passing

app/controllers/admin/users_controller.rb, app/controllers/merchants_controller.rb, app/views/admin/users/show.html.erb, app/views/layouts/application.html.erb, app/views/merchants/show.html.erb, config/routes.rb, spec/features/users/navigation_spec.rb
- Admin-nav branch was created off of merchant-nav branch.
- Merge merchant-nav branch first and then admin-nav branch.
Closes User Story 5:
As an admin user
I see the same links as a visitor
Plus the following links
- a link to my admin dashboard ("/admin/dashboard")
- a link to log out ("/logout")
Minus the following links/info:
- I do not see a link to log in or register
- a link to my shopping cart ("/cart") or count of cart items
- Created admin navigation bar
- Updated routes.rb (namespace for admin dashboard), user navigation tests.
=> !!MERGE AFTER MERCHANT-NAV!!

app/controllers/users_controller.rb, app/views/users/show.html.erb, config/routes.rb, db/seeds.rb, spec/features/users/profile_spec.rb
Closes User Story 17 (#103)
As a registered user
When I visit my own profile page
Then I see all of my profile data on the page except my password
And I see a link to edit my profile data
- Created user profile feature test
- Added profile info to user show page
- Created user edit route
- All user profile tests passing
=> User profile

app/controllers/admin/users_controller.rb, app/controllers/merchants_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, spec/features/users/login_spec.rb, spec/features/users/registration_spec.rb
Closes User Story 11:
As a visitor
When I visit the login page ("/login")
And I submit invalid information
Then I am redirected to the login page
And I see a flash message that tells me that my credentials were incorrect
I am NOT told whether it was my email or password that was incorrect
- Adds test for password mismatch and username/password do not exist.
- Updated create action in SessionsController to include flash message.
- Feature tests passing.
=> completes user story 11

app/controllers/admin/users_controller.rb, app/controllers/merchants_controller.rb, app/controllers/welcome_controller.rb, app/views/layouts/application.html.erb, app/views/merchants/show.html.erb, spec/features/merchants/show_spec.rb, spec/features/users/navigation_spec.rb, spec/features/users/registration_spec.rb
Closes User Story 34:
As a merchant user
When I visit my dashboard ("/dashboard")
I see my profile data, but cannot edit it
- Adds test for merchant profile info on merchant show page.
- Adds test to ensure merchant cannot edit profile info.
- Updated application.html.erb and WelcomeController to dry up nav bar and comply with relevant user stories
- All navigation feature tests passing
=> Merchants show

app/controllers/admin/merchants_controller.rb, app/controllers/admin/users_controller.rb, app/controllers/merchants_controller.rb, app/models/user.rb, app/views/merchants/index.html.erb, config/routes.rb, spec/features/merchants/index_spec.rb, spec/models/user_spec.rb
Closes #75 
- Change controllers to user current_user
- Add to MerchantsController#current_admin to find all merchants
- Add method to test and index to clean up time display.
=> 41 admin visits merchant index page

spec/features/users/registration_spec.rb, spec/models/user_spec.rb
During the merge for story 41, we missed that the test set up for my user model test for .all_merchants had been removed. I added it back and it is now passing. spec/features/users/registration_spec.rb is still failing- please compare with another version before merging.
=> .all_merchants method test now passing

app/controllers/sessions_controller.rb, spec/features/users/login_spec.rb, spec/features/users/logout_spec.rb
Closes #110 User Story 12
- Add test for login_path if already logged in and where to be redirected
- Add logic to SessionsController#new to redirect users and send flash message
- Feature tests related to user story are passing.
=> 12 users already logged in are redirected

app/controllers/admin/users_controller.rb, app/models/user.rb, app/views/admin/users/index.html.erb, app/views/layouts/application.html.erb, config/routes.rb, spec/features/admins/user_index_spec.rb, spec/models/user_spec.rb
- Add feature test for admin user index page
- Add link for name, button to upgrade to merchant, date registered info in the index page
- Add model test and method to retrieve all users (not merchants or admin)
- Restricted access to page to only admins
=> User Story 55: Admin User Index Page

app/controllers/users_controller.rb, app/views/users/edit.html.erb, app/views/users/show.html.erb, config/routes.rb, spec/features/users/edit_profile_spec.rb, spec/features/users/profile_spec.rb, spec/features/users/registration_spec.rb
Closes User Story 18 and 19:
As a registered user
When I visit my profile page
I see a link to edit my profile data
When I click on the link to edit my profile data
Then my current URI route is "/profile/edit"
I see a form like the registration page
The form contains all of my user information
The password fields are blank and can be left blank
I can change any or all of the information
When I submit the form
Then I am returned to my profile page
And I see a flash message telling me that my data is updated
And I see my updated information
If I try to change my email address to one that belongs to another user
When I submit the form
Then I am returned to the profile edit page
And I see a flash message telling me that email address is already in use
- Created functionality and feature tests …
=> Completes User Stories 18 and 19

config/routes.rb, spec/features/users/navigation_spec.rb
=> Fixed some general testing issues

app/controllers/application_controller.rb, app/controllers/carts_controller.rb, app/models/cart.rb, app/views/items/show.html.erb, app/views/layouts/application.html.erb, config/routes.rb, spec/features/cart/cart_spec.rb, spec/models/cart_spec.rb
- Add feature test for adding items to cart and incrementing the number in the nav bar
- Created Cart model with total_count method for cart items
- Add create route for /carts
- All tests passing!
=> User Story 20: User Adds an Item to the Cart

app/controllers/orders_controller.rb, app/models/order.rb, app/views/orders/index.html.erb, app/views/orders/show.html.erb, app/views/users/show.html.erb, config/routes.rb, spec/features/orders/index_spec.rb, spec/features/orders/show_spec.rb, spec/features/users/navigation_spec.rb, spec/features/users/profile_spec.rb
Closes User Stories 27, 28,29:
27: As a registered user
When I visit my Profile page
And I have orders placed in the system
Then I see a link on my profile page called "My Orders"
When I click this link my URI path is "/profile/orders"
28: 
When I visit my Profile Orders page, "/profile/orders"
I see every order I've made, which includes the following information:
- the ID of the order, which is a link to the order show page
- the date the order was made
- the date the order was last updated
- the current status of the order
- the total quantity of items in the order
- the grand total of all items for that order
29:
My URL route is now something like "/profile/orders/15"
I see all information about the order, including the following information:
- the ID of the order
- the date the order …
=> Completes User Stories 27, 28, 29

app/models/order_item.rb, app/models/user.rb, spec/features/orders/show_spec.rb
Upon merging we encountered an error and this fixes it. The error involved divide by zero on the avg fulfillment.
=> additionToCalculationAvgFulfillment

app/controllers/carts_controller.rb, app/views/carts/show.html.erb, config/routes.rb, spec/features/cart/cart_spec.rb
- Add test to see that carts is cleared
- Add route carts#destroy
Co-authored-by: Jalena Penaligon <45905026+jalena-penaligon@users.noreply.github.com>
=> User Story 23: User Can Empty Cart

app/controllers/carts_controller.rb, app/views/carts/show.html.erb, config/routes.rb, spec/features/cart/cart_spec.rb
- Closes #95 
- Add tests for incrementing and decrementing items in cart
- Add links for Delete Item, Add One and Delete One
- Add route carts#destroy and carts#update
- Add carts_controller#destroy and carts_controller#update
=> User Story 24: User an manipulate quantities in cart

app/controllers/merchants/orders_controller.rb, app/controllers/orders_controller.rb, app/models/item.rb, app/models/order.rb, app/models/order_item.rb, app/models/user.rb, app/views/merchants/orders/show.html.erb, app/views/merchants/show.html.erb, app/views/orders/show.html.erb, config/routes.rb, spec/features/merchants/show_spec.rb, spec/features/orders/show_spec.rb
As a merchant
When I visit an order show page from my dashboard
I see the customer's name and address
I only the items in the order that are being purchased from my inventory
I do not see any items in the order being purchased from other merchants
For each item, I see the following information:
- the name of the item, which is a link to my item's show page
- a small thumbnail of the item
- my price for the item
- the quantity the user wants to purchase
=> adds user story 52

app/controllers/merchants/order_items_controller.rb, app/models/item.rb, spec/features/items/index_spec.rb, spec/features/merchants/orders/show_spec.rb, spec/features/users/navigation_spec.rb
adds error resolution after merging many stories.
Co-authored-by: Erin King <44042415+erin-king@users.noreply.github.com>
Co-authored-by: Jalena Taylor <45905026+jalena-penaligon@users.noreply.github.com>
Co-authored-by: Smitha Hosmana <32909448+hsmitha26@users.noreply.github.com>
=> error resolution as a group

app/controllers/merchants/items_controller.rb, app/views/merchants/show.html.erb, config/routes.rb, spec/features/merchants/show_spec.rb
Closes User Story 37:
As a merchant
When I visit my dashboard
I see a link to view my own items
When I click that link
My URI route should be "/dashboard/items"
Created: test, new route for /dashboard/items, items_controller within merchants controller folder
- Implemented link to My Items for each merchant.
Co-authored-by: Jalena Taylor <45905026+jalena-penaligon@users.noreply.github.com>
=> Adds test and functionality for user story 37

app/controllers/admin/merchants_controller.rb, app/models/user.rb, app/views/admin/merchants/show.html.erb, spec/features/admins/merchants/index_spec.rb
Completes User Story 38
As an admin user
When I visit the merchant index page ("/merchants")
And I click on a merchant's name,
Then my URI route should be ("/admin/merchants/6")
Then I see everything that merchant would see
Adds: feature test, admin-merchant show page
Changed: User model ::all_users to order by :id.
All tests are passing.
Co-authored-by: Jalena Taylor <45905026+jalena-penaligon@users.noreply.github.com>
=> Admin merchant dashboard 38

app/controllers/merchants/items_controller.rb, app/models/item.rb, app/models/order_item.rb, app/views/layouts/application.html.erb, app/views/merchants/items/index.html.erb, config/routes.rb, spec/features/merchants/items/index_spec.rb, spec/features/users/logout_spec.rb, spec/models/item_spec.rb
- Remove GET '/logout' from routes- destroy is enough (Megan's comment)
- Add tests for user story- items, info, enable/disable buttons, delete buttons
- Add required elements to merchant items index page
- Add method not_ordered? to items model, called in index
=> User Story 44: Merchant Items Index Page

config/routes.rb
Co-authored-by: Jalena Taylor <45905026+jalena-penaligon@users.noreply.github.com>
Co-authored-by: Erin King <44042415+erin-king@users.noreply.github.com>
Co-authored-by: Jennica Stiehl <25069483+stiehlrod@users.noreply.github.com>
=> Fixed error due to duplication of a route.

app/controllers/orders_controller.rb, app/views/orders/show.html.erb, config/routes.rb, spec/features/orders/show_spec.rb
Closes User Story 30
- Adds update method to OrdersController
- Adds :update route to user/orders
- Adds "Cancel Order" button to pending orders in User Orders Show Page
- Creates test that pending orders can be cancelled 
As a registered user
When I visit an order's show page
If the order is still "pending", I see a button or link to cancel the order
When I click the cancel button for an order, the following happens:
- Each row in the "order items" table is given a status of "unfulfilled"
- The order itself is given a status of "cancelled"
- Any item quantities in the order that were previously fulfilled have their quantities returned to their respective merchant's inventory for that item.
- I am returned to my profile page
- I see a flash message telling me the order …
=> Creates functionality for a user to cancel pending orders

app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/merchants/index.html.erb, config/routes.rb, spec/features/merchants/index_spec.rb
- Add tests for feature
- Add route to users_controller "toggle_merchant"
- Add action for users_controller  "active_toggle"
- Add restriction to sessions_controller to stop "inactive" users(merchants) from logging in
- All tests passing.
=> User Story 42 & 43: Admin disables/enables merchant account

app/controllers/items_controller.rb, app/views/merchants/items/index.html.erb, config/routes.rb, spec/features/merchants/items/index_spec.rb
- Add tests for disabling and enabling items form merchant items page
- Add toggle path and method to items controller
=> User Story 45 & 46: Merchant disables/enables an item

app/controllers/admin/merchants_controller.rb, app/controllers/admin/users_controller.rb, spec/features/admins/merchants/show_spec.rb
Opposite of User Story 60. MERGE 60 FIRST
- Add test to check for correct redirect
- Add conditional statement in admin/user_controller#show to redirect if user is actually a merchant
- All tests passing.
=> User Story 58: Admin Redirected from User Profile to Merchant Dashboard

.gitignore, app/controllers/application_controller.rb, app/controllers/carts_controller.rb, app/models/cart.rb, app/models/order_item.rb, app/views/carts/show.html.erb, spec/models/cart_spec.rb
Fixes cart to bring coverage to 100%
=> Brings cart model coverage to 100%

app/controllers/merchants_controller.rb, app/models/item.rb, app/models/order_item.rb, app/models/user.rb, app/views/merchants/show.html.erb, spec/features/merchants/dashboard_stats_spec.rb, spec/models/item_spec.rb, spec/models/order_item_spec.rb, spec/models/user_spec.rb
adds work towards improving test coverage.
=> adds testing

app/models/order_item.rb
=> adds bug fix

app/views/sessions/new.html.erb
- Changed text_field_tag with password_field_tag- entered password is now dots, not the text.
=> Bug: Login Page Password Field

app/controllers/application_controller.rb, app/views/items/show.html.erb, spec/features/items/show_spec.rb
Added conditional to items show page to not show Add to Cart to merchants and admins.
=> Bug: Add cart link should not show for merchant of admin

app/assets/stylesheets/application.css, app/controllers/merchants/order_items_controller.rb, app/controllers/merchants/orders_controller.rb, app/models/user.rb, app/views/merchants/orders/show.html.erb, app/views/merchants/show.html.erb, db/seeds.rb, spec/features/merchants/dashboard_stats_spec.rb, spec/features/merchants/orders/show_spec.rb, spec/features/orders/show_spec.rb
Fixed iteration bugs for user & merchant orders.
=> Added label for item quantity for readability

app/models/order.rb, app/views/orders/show.html.erb
Add to grand_total method to calculate order_price by order_quantity.
=> Bug: total order price correction

app/assets/stylesheets/application.css, app/controllers/admin/merchants_controller.rb, app/controllers/merchants/items_controller.rb, app/models/user.rb, app/views/admin/admin/show.html.erb, app/views/admin/merchants/show.html.erb, app/views/admin/users/index.html.erb, app/views/admin/users/show.html.erb, app/views/carts/show.html.erb, app/views/items/show.html.erb, app/views/layouts/application.html.erb, app/views/merchants/index.html.erb, app/views/merchants/items/index.html.erb, app/views/merchants/orders/show.html.erb, app/views/merchants/show.html.erb, app/views/orders/index.html.erb, app/views/orders/show.html.erb, app/views/sessions/new.html.erb, app/views/users/edit.html.erb, app/views/users/new.html.erb, app/views/users/show.html.erb, app/views/welcome/index.html.erb, spec/features/admins/orders/index_spec.rb, spec/features/merchants/dashboard_stats_spec.rb, spec/features/merchants/show_spec.rb, spec/models/user_spec.rb
Completes styling and final bug fixes, all tests passing.
=> Completes styling
